import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/custom/navbar";
import WhatsappButton from "@/components/ui/custom/whatsapp-button";
import Footer from "@/components/ui/custom/footer";

export const metadata: Metadata = {
  title: "Inkmind Tatoos",
  description: "Generated by Landing Template",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <WhatsappButton href="https://wa.me/+972528114746" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
